# FTP Deployment Configuration
FTP_HOST="m115436.serverpark.dk"
FTP_USER="i46130_halloween"
FTP_PASS="Benediktevej123"

# The directory on the server where the files should be uploaded. Leave empty if rooted to the target dir.
REMOTE_DIR=""